# Generated by Django 5.1.6 on 2025-02-17 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
